### ISSUE TITLE
'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by madisonschott** [rfdearborn/dbt-docs-to-notion#15]
`Notice:  A new release of pip is available: 22.0.4 -> 23.1
Notice:  To update, run: pip install --upgrade pip
Run dbt deps --profiles-dir ./ --target=github_actions
21:08:29  Encountered an error:
'str' object has no attribute 'get'
21:08:29  Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/dbt/main.py", line 136, in main
    results, succeeded = handle_and_check(args)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/dbt/main.py", line 180, in handle_and_check
    user_config = read_user_config(flags.PROFILES_DIR)  # This is read again later
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/dbt/config/profile.py", line 74, in read_user_config
    user_config = coerce_dict_str(profile.get("config", {}))
AttributeError: 'str' object has no attribute 'get'`

**Comment by rfdearborn** [comment]
Hmm, looks like a profiles issue -- can you confirm that your setup includes the below bit and that `secrets.DBT_PROFILES` is configured? Should be a straight copy-paste of `.dbt/profiles.yml`.

```
      - name: Create temp dbt profiles
        run: "printf %s \"$DBT_PROFILES\" > ./profiles.yml"
        env:
          DBT_PROFILES: ${{ secrets.DBT_PROFILES }}
```
