### ISSUE TITLE
Specifying specific model not working

### ISSUE THREAD

**Issue by SimonSchmitke** [rfdearborn/dbt-docs-to-notion#18]
### Context
I use dbt + Snowflake. This successfully works and writes to Notion when I use `model-records-to-write: "all"`, but does not work when choosing a specific model, such as `stg_accounts`.

### What I've tried
I've tried combinations in the workflow below, such as:
```
      - name: dbt-docs-to-notion
        uses: rfdearborn/dbt-docs-to-notion@v1.0.9
        with:
          dbt-package: 'dbt-snowflake==1.4.1'
          dbt-target: 'notion'
          model-records-to-write: <Update this>
          ...
```

and I've entered:
- `model-records-to-write: "stg_accounts"`
- `model-records-to-write: "STG_ACCOUNTS"`
- `model-records-to-write: "my_database.schema.stg_accounts"`
- `model-records-to-write: "MY_DATABASE.SCHEMA.STG_ACCOUNTS"`
- `model-records-to-write: "schema.stg_accounts"`
- `model-records-to-write: "SCHEMA.STG_ACCOUNTS"`

and tried single quotes for all of the above, but none of these work. No errors show up in the workflow. Not sure what to do.

Any ideas?
